apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8sdemo
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
        - name: k8sdemo
          image: newdelthis/k8sdemo:1.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-service
spec:
  type: LoadBalancer      # 1. Changed from NodePort to LoadBalancer
  selector:
    app: k8sdemo
  ports:
    - port: 80            # The port the external Cloud Load Balancer will listen on
      targetPort: 8080    # The port your container is listening on
      # The 'nodePort' line has been removed. Kubernetes will automatically 
      # assign a random port (30000-32767) behind the scenes for the Cloud LB to use.
